/**
 * @file ala-util 合并文件
 * @author cxtom <cxtom2008@gmail.com>
 */

/* global __inlinePackage, __inline */

define("@baidu/ala-util/update",["require","@baidu/ala-util/lodash"],function(a){function r(a){return Array.isArray(a)?a.concat():a&&"object"==typeof a?t(new a.constructor,a):a}var t=a("@baidu/ala-util/lodash").assign,n=Object.prototype.hasOwnProperty,c="$push",e="$unshift",l="$splice",u="$set",i="$merge",o="$apply",p=[c,e,l,u,i,o],s=p.reduce(function(a,r){return a[r]=!0,a},{});return function f(a,p){if(n.call(p,u))return p[u];var h=r(a);n.call(p,i)&&t(h,p[i]),n.call(p,c)&&p[c].forEach(function(a){h.push(a)
}),n.call(p,e)&&(h=p[e].concat(h)),n.call(p,l)&&p[l].forEach(function(a){h.splice.apply(h,a)}),n.call(p,o)&&(h=p[o](h));for(var d in p)s.hasOwnProperty(d)&&s[d]||(h[d]=f(a[d],p[d]));return h}});;
define("@baidu/ala-util/ala",["require","@baidu/ala-util/lodash","@baidu/ala-util/index"],function(r){function e(r){if(!r)return!1;r=r.replace(/&amp;/g,"&");var e={};return e.query=r.replace(/([^?]+)\?/g,function(r,t){return e.path=t,""}).replace(/#.*/,function(r){return e.hash=r,""}),e.params={},e.query.split("&").forEach(function(r){var t=r.split("=");t[0]&&(e.params[t[0]]=t.length>1?decodeURIComponent(t[1]):"")}),e}function t(r){if(u)return!0;if(!r)return!1;r=r.replace(/&amp;/g,"&");var t=e(r),a=t.params.tj;
if(a){var n=a&&a.split("_")[4],c=n.match(/(\w+)(\d+)/);if(c){var o={};o[c[1]]=c[2],i(o)}}return!f&&i({l:0}),u=t,!0}function i(r){f||(f={}),h.forEach(r,function(r,e){f[e]=+r?+r:1})}function a(r){return void 0===r||null===r||""===r}function n(r,e,t){var i,a=h.isArray(e),c=h.isPlainObject(e);for(var o in e)if(e.hasOwnProperty(o)){var s=e[o];i=h.isObject(s)||h.isArray(s),t&&(o=t+"["+(c||i?o:"")+"]"),!t&&a?r.add(s.name,s.value):i?n(r,s,o):r.add(o,s)}}function c(r){var e=window.location.href;e=decodeURIComponent(e);
for(var t=e.split("&"),i=0;i<t.length;i++){var n=t[i];if(!a(n)){var c=n.split("=");if(c[0]===r&&!a(c[0])&&!a(c[1]))return c[1]}}}function o(r){var e=[],t=encodeURIComponent;return e.add=function(r,e){h.isFunction(e)&&(e=e()),null===e&&(e=""),this.push(t(r)+"="+t(e))},n(e,r),e.join("&").replace(/%20/g,"+")}function s(r,e){var t={type:"",mipUrl:"",cacheUrl:"",baiduUrl:"",mainUrl:"",isHttps:!1,hasQuery:!1},i="https://mipcache.bdstatic.com/c/",a="https://m.baidu.com/mip/c/";e&&(a="https://m.baidu.com/"+e+"/c/");
var n,c;return 0===r.indexOf(i)?(t.type="MIP-Cache Url",n=new RegExp(i+"(s/)?(\\S+)")):0===r.indexOf(a)?(t.type="Baidu Url",n=new RegExp(a+"(s/)?(\\S+)")):(t.type="MIP Url",n=new RegExp("http(s)?://(\\S+)")),(c=n.exec(r))?(c[1]&&(t.isHttps=!0),t.mainUrl=p(c[2]),t.mipUrl="http"+(t.isHttps?"s":"")+"://"+t.mainUrl,t.cacheUrl=i+(t.isHttps?"s/":"")+t.mainUrl,t.baiduUrl=a+(t.isHttps?"s/":"")+l(t.mainUrl),t):!1}function l(r){var e=encodeURIComponent(r);e=e.replace(/%2F/g,"/");for(var t=0;t<e.length;t++){var i=e.charAt(t),a=e.charAt(t+1);
if("/"!==i||"/"===a)for(;"/"===e.charAt(t)&&t<e.length;)e=e.slice(0,t)+"%2F"+e.slice(t+1),t+=3}return e}function p(r){var e=r.replace(new RegExp("/","g"),"%2F");return decodeURIComponent(e)}function m(r){var e;return r&&"string"==typeof r?e=r:r&&r.url&&(e=r.url),e}function d(r,e){if(!/\/s\?/.test(r))return!1;var t=x.URL.parse(r),i=t.query;return i.word?(i.query=i.word,delete i.word,i.asctag=(new Date).getTime(),g.makeSearchLink(i,e,!0)):!1}var u,f,h=r("@baidu/ala-util/lodash"),x=r("@baidu/ala-util/index"),g={makeTcLink:function(r,e,n){if("pc"===e.env){var s=m(r.url||r.src),l={type:"tc",tcUrl:s};
return n?l:l.tcUrl}if(!t(e.asyncTcUrl))throw new Error("makeTcLink parameter error.");var p="l",d=e.srcid+"_"+e.order+"_"+page.comm.pn+"_"+page.comm.rn+"_";if(r.tjType&&(p=r.tjType,delete r.tjType),r.tj5)r.tj=d+r.tj5,delete r.tj5;else{if(!f[p]){var x={};x[p]=0,i(x)}r.tj=d+p+f[p]++}r.extra&&r.extra.length>10&&(r.extra=r.extra.slice(0,10));var g;"wise"===e.env?g=e.order:"sf"===e.env&&(g=c("frorder"));var v=h.assign({isAtom:1,order:g},u.params,r);a(r.url)||(a(r.url.rloc)||(v.rloc=r.url.rloc),delete v.url),a(r.nsrc)||(v.nsrc=r.nsrc),a(v.nsrc)||(h.assign(v,{bdenc:1}),delete v.src),h.forEach(v,function(r,e){a(r)&&delete v[e]
});var y=o(v),w=u.path+"?"+y;"https:"===location.protocol&&/^http:\/\/m.baidu.com\//.test(w)&&(w=w.replace(/^http/,"https"));var l={type:"tc",tcUrl:w},k=m(r.url||r.src);if(k&&/^https?:\/\/[^\/]*\.baidu\.com\//.test(k)&&!r.isXcx){l.originUrl=k;var U={};r.nsrc?U.e=r.nsrc:U.mu=k,r.cyc&&(U.c=r.cyc),r.extra&&(U.extra=r.extra),l.log=JSON.stringify(U),r.isSf&&(l.type="sf")}var b=r.xcxParams;if(r.isXcx&&b){l.type="xcx",l.options={xcxAppKey:b.appkey,xcxPath:b.path,xcxQuery:b.query,xcxFrom:b.from,xcxExt:b.ext,xcxUrl:b.url};
var j=b.query?"?"+b.query:"",E="http://xcx.baidu.com"+b.path+j;l.log=JSON.stringify({mu:E}),l.clickData=JSON.stringify({clk_info:{type:"xcx",xcx_id:b.appkey,xcx_from:b.from},cyc:1}),l.originUrl=k}return n===!0?l:l.tcUrl},makeSearchLink:function(r,e,t){r=h.assign({sa:"re_"+e.order+"_"+e.srcid,prefix:location.protocol+"//"+location.host},r),"/"===r.prefix.slice(-1)&&(r.prefix=r.prefix.slice(0,-1));var i={sa:r.sa.substr(0,15)};t!==!0?["st","euri","prese"].forEach(function(e){r[e]&&(i[e]=r[e])}):(i=h.assign({},x.omit(r,["prefix","query","sa"]),i),i=h.reduce(i,function(r,e,t){return r[encodeURIComponent(t)]=encodeURIComponent(e),r
},{}));var a=page.utils.link.getSearchUrl(r.query,i);return-1===a.indexOf(r.prefix)&&(a=r.prefix+a),a},makeSearchTcLink:function(r,e){return this.makeTcLink({src:this.makeSearchLink(r,e),tjType:r.tjType,tj5:r.tj5},e)},makeSfLink:function(r,e){var t=m(r.url),i={mu:t};r.cyc&&(i.c=r.cyc),r.extra&&r.extra.length>10&&(r.extra=r.extra.slice(0,10)),r.extra&&(i.extra=r.extra);var a,n=d(t,e);n?(a=n.replace(/^http(s)?:\/\/[^\/]+/,""),r.options='{"useWebview": false}'):(/word=/.test(t)||(t+="&word="+e.word),/title=/.test(t)||(t+="&title="+e.word),a=t.replace(/^http(s)?:\/\/m.baidu.com/,"")+"&lid="+e.lid+"&ms=1",a+="&frsrcid="+e.srcid,a+="&frorder="+e.order,r.anchor&&(a+="#"+r.anchor));
var c={type:"sf",sfUrl:a,options:r.options,log:JSON.stringify(i),tcUrl:this.makeTcLink({src:location.protocol+"//"+location.host+a,cyc:r.cyc,extra:r.extra},e)};return c},makeMipLink:function(r,e){var t=m(r.url),i={mu:t};if(r.cyc&&(i.c=r.cyc),r.extra&&r.extra.length>10&&(r.extra=r.extra.slice(0,10)),r.extra&&(i.extra=r.extra),!t||!/^http(s)?:\/\//.test(t))throw new Error('makeMipLink parameter error: "url" or "url.url" can not be empty, and must start with "http://" or "https://".');if(!r.title)throw new Error('makeMipLink parameter error: "title" can not be empty.');
var a=page.comm.mipAladdinPrefix;r.isInstanceServices&&(a=page.comm.mipInstantServicesPrefix);var n=s(t,a);if(!n)throw new Error("makeMipLink parameter error: wrong url format.");var c=n.baiduUrl.slice("https://m.baidu.com".length),o="",l=t.indexOf("#");l>=0&&l<t.length-1&&(o=t.slice(l+1)+"&");var p="#"+o,d=p+["word=",e.word,"&lid=",e.lid,"&srcid=",e.srcid,"&mipanchor=",o].join(""),u={title:r.title,lid:e.lid,mipCustomHash:encodeURIComponent(d)};return{type:"sf",sfUrl:c,options:JSON.stringify(u),log:JSON.stringify(i),tcUrl:this.makeTcLink({src:location.protocol+"//m.baidu.com"+c,cyc:r.cyc,extra:r.extra},e)}
},makeTimg:function(r){var t;if(page.comm.timgPre&&(t=e(page.comm.timgPre)),!t||!r.imgsrc)throw new Error("makeTimg parameter error!");var i,a=h.assign({},t.params,{size:r.cuttype||void 0,quality:r.size||60,src:r.imgsrc,di:r.di,sec:r.sec});return i=t.path+"?"+o(a)},highLight:function(r,e){a(e)&&(e=window.bds?bds.comm.query:page.comm.query),e=decodeURIComponent(e);var t=new RegExp("("+e+")","ig");return r.replace(t,function(r,e){return"<em>"+e+"</em>"})},getHttpsHost:function(r){var e=window.bds?bds.util.domain:page.https.domain;
return e.get(r)},setHttpsHost:function(r,e){if(/^http:\/\//.test(r)||/^https:\/\//.test(r)||/^\/\//.test(r))throw new Error('setHttpsHost parameter error: kdomain should not start with "http(s)://".');if(!/^https:\/\//.test(e))throw new Error('setHttpsHost parameter error: vdomain should start with "https://".');var t=window.bds?bds.util.domain:page.https.domain;t.set(r,e)},sendLog:function(r,e,t){if("pc"!==e.env){var i={srcid:e.srcid,tplname:e.tplname};if(r.extra&&r.extra.length>10&&(r.extra=r.extra.slice(0,10)),"wise"===e.env){h.assign(i,{type:"o",t:+new Date},r),delete i.src;
var n={},c=["ct","cst","clk_from","clk_extra","extra","cyc","hwj"];c.forEach(function(r){a(i[r])||(n[r]=i[r],delete i[r])}),h.assign(n,{fm:r.fm||"alop",clk_info:JSON.stringify(i),order:e.order,ala_clk:[e.ensrcid,e.order,page.comm.pn,page.comm.rn,"o"].join("_")}),r.src&&(n.src=r.src),A.log.send(A.getLogUrl(n))}else if("sf"===e.env){if(!t||!t.comm||!t.log)throw new Error("sendLog parameter error: viewPage.");var o={c:"cyc",e:"nsrc",m:"mip",ct:"ct",cst:"cst",hwj:"hwj",clk_from:"clk_from",clk_extra:"clk_extra",extra:"extra"},s={order:e.order};
for(var l in o)l in r&&("m"!==l?s[o[l]]=r[l]:r[o[l]]=r[l],delete r[l]);s.nsrc&&(s.bdenc=1),h.assign(r,i,{referlid:t.comm.referlid,applid:t.comm.applid,frsrcid:t.comm.frsrcid,frorder:t.comm.frorder}),delete r.link,t.log.sendInfo(r,s)}}}};return g});;
define("@baidu/ala-util/env",["require","exports"],function(n,t){function r(n,t){var r=this.os={},e=this.browser={},o=n.match(/Web[kK]it[\/]{0,1}([\d.]+)/),i=n.match(/(Android);?[\s\/]+([\d.]+)?/),u=!!n.match(/\(Macintosh\; Intel /),a=n.match(/(iPad).*OS\s([\d_]+)/),c=n.match(/(iPod)(.*OS\s([\d_]+))?/),f=!a&&n.match(/(iPhone\sOS)\s([\d_]+)/),l=n.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),s=/Win\d{2}|Windows/.test(t),p=n.match(/Windows Phone ([\d.]+)/),h=l&&n.match(/TouchPad/),d=n.match(/Kindle\/([\d.]+)/),v=n.match(/Silk\/([\d._]+)/),m=n.match(/(BlackBerry).*Version\/([\d.]+)/),g=n.match(/(BB10).*Version\/([\d.]+)/),b=n.match(/(RIM\sTablet\sOS)\s([\d.]+)/),y=n.match(/PlayBook/),w=n.match(/Chrome\/([\d.]+)/)||n.match(/CriOS\/([\d.]+)/),_=n.match(/Firefox\/([\d.]+)/),j=n.match(/\((?:Mobile|Tablet); rv:([\d.]+)\).*Firefox\/[\d.]+/),O=n.match(/MSIE\s([\d.]+)/)||n.match(/Trident\/[\d](?=[^\?]+).*rv:([0-9.].)/),T=!w&&n.match(/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/),A=T||n.match(/Version\/([\d.]+)([^S](Safari)|[^M]*(Mobile)[^S]*(Safari))/);
(e.webkit=!!o)&&(e.version=o[1]),i&&(r.android=!0,r.version=i[2]),f&&!c&&(r.ios=r.iphone=!0,r.version=f[2].replace(/_/g,".")),a&&(r.ios=r.ipad=!0,r.version=a[2].replace(/_/g,".")),c&&(r.ios=r.ipod=!0,r.version=c[3]?c[3].replace(/_/g,"."):null),p&&(r.wp=!0,r.version=p[1]),l&&(r.webos=!0,r.version=l[2]),h&&(r.touchpad=!0),m&&(r.blackberry=!0,r.version=m[2]),g&&(r.bb10=!0,r.version=g[2]),b&&(r.rimtabletos=!0,r.version=b[2]),y&&(e.playbook=!0),d&&(r.kindle=!0,r.version=d[1]),v&&(e.silk=!0,e.version=v[1]),!v&&r.android&&n.match(/Kindle Fire/)&&(e.silk=!0),w&&(e.chrome=!0,e.version=w[1]),_&&(e.firefox=!0,e.version=_[1]),j&&(r.firefoxos=!0,r.version=j[1]),O&&(e.ie=!0,e.version=O[1]),A&&(u||r.ios||s)&&(e.safari=!0,r.ios||(e.version=A[1])),T&&(e.webview=!0),r.tablet=!!(a||y||i&&!n.match(/Mobile/)||_&&n.match(/Tablet/)||O&&!n.match(/Phone/)&&n.match(/Touch/)),r.phone=!(r.tablet||r.ipod||!(i||f||l||m||g||w&&n.match(/Android/)||w&&n.match(/CriOS\/([\d.]+)/)||_&&n.match(/Mobile/)||O&&n.match(/Touch/)))
}r.call(t,navigator.userAgent,navigator.platform)}),define("@baidu/ala-util/es6-promise",["require"],function(){return window.Promise}),define("@baidu/ala-util/fetch-jsonp",["require","@baidu/ala-util/es6-promise"],function(n){"use strict";function t(){return"jsonp_"+Date.now()+"_"+Math.ceil(1e5*Math.random())}function r(n){try{delete window[n]}catch(t){window[n]=void 0}}function e(n){var t=document.getElementById(n);t&&document.getElementsByTagName("head")[0].removeChild(t)}function o(n){var o=arguments.length<=1||void 0===arguments[1]?{}:arguments[1],a=n,c=o.timeout||u.timeout,f=o.jsonpCallback||u.jsonpCallback,l=void 0;
return new i(function(u,s){var p=o.jsonpCallbackFunction||t(),h=f+"_"+p;window[p]=function(n){u({ok:!0,json:function(){return i.resolve(n)}}),l&&clearTimeout(l),e(h),r(p)},a+=-1===a.indexOf("?")?"?":"&";var d=document.createElement("script");d.setAttribute("src",""+a+f+"="+p),o.charset&&d.setAttribute("charset",o.charset),d.id=h,document.getElementsByTagName("head")[0].appendChild(d),l=setTimeout(function(){s(new Error("JSONP request to "+n+" timed out")),r(p),e(h)},c),d.onerror=function(){s(new Error("JSONP request to "+n+" failed")),r(p),e(h),l&&clearTimeout(l)
}})}var i=n("@baidu/ala-util/es6-promise"),u={timeout:5e3,jsonpCallback:"callback",jsonpCallbackFunction:null};return o}),define("@baidu/ala-util/fetch",["require"],function(){return window.fetch}),define("@baidu/ala-util/index",["require","@baidu/ala-util/lodash","@baidu/ala-util/env","@baidu/ala-util/fetch-jsonp","@baidu/atom-web-runtime","@baidu/ala-util/es6-promise","@baidu/ala-util/fetch"],function(n){function t(n,t){var r={};t=Array.isArray(t)?t:[t];for(var e in n)t.indexOf(e)>=0||Object.prototype.hasOwnProperty.call(n,e)&&(r[e]=n[e]);
return r}function r(n,t,e){var o,u=i.isArray(t),a=i.isPlainObject(t);for(var c in t)if(t.hasOwnProperty(c)){var f=t[c];o=i.isObject(f)||i.isArray(f),e&&(c=e+"["+(a||o?c:"")+"]"),!e&&u?n.add(f.name,f.value):o?r(n,f,c):n.add(c,f)}}function e(n){var t={};try{window[n].setItem("_t",1),window[n].removeItem("_t"),t.enabled=!0}catch(r){t.enabled=!1}if(!t.enabled)return{enabled:!1,storgae:{},setItem:function(n,t){this.storgae[n]=t},removeItem:function(n){null!=this.storgae[n]&&delete this.storgae[n]},getItem:function(n){return this.storgae[n]
}};var e=window[n],o="search_ala_";return t.getItem=function(n){return e.getItem(o+n)},t.setItem=function(n,t){e.setItem(o+n,t)},t.removeItem=function(n){e.removeItem(o+n)},t}var o={},i=o=n("@baidu/ala-util/lodash"),u=n("@baidu/ala-util/env"),a=n("@baidu/ala-util/fetch-jsonp"),c=n("@baidu/atom-web-runtime");o.os=u.os,o.browser=u.browser;var f=o.Promise=n("@baidu/ala-util/es6-promise"),l=n("@baidu/ala-util/fetch"),s={mode:"same-origin",credentials:"same-origin"},p={jsonpCallback:"cb"},h=o.URL={};o.omit=t,o.fetch=function(n,r){var e=r.data,o=(r.method||"get").toLowerCase();
switch(r=i.assign({},"jsonp"===o?p:s,t(r,["data"])),o){case"get":r.headers=i.assign({"Content-Type":"application/json; charset=UTF-8"},r.headers);case"jsonp":e&&(n+=(n.indexOf("?")>=0?"&":"?")+h.params(e));break;case"post":"undefined"!=typeof FormData&&r.body instanceof FormData||(r.headers=i.assign({"Content-Type":"application/x-www-form-urlencoded"},r.headers),e&&!r.body&&(r.body=h.params(e)))}var c="jsonp"===o?a(n,r):l(n,r);return c.then(function(n){var t=n.status,r=n.statusText;return u.browser.qq&&"boolean"!=typeof n.ok&&(n.ok=+t>=200&&300>+t),n.json().then(function(t){if(n.ok)return t;
throw new Error(r)})})},h.params=function(n){var t=[],e=encodeURIComponent;return t.add=function(n,t){i.isFunction(t)&&(t=t()),null===t&&(t=""),this.push(e(n)+"="+e(t))},r(t,n),t.join("&").replace(/%20/g,"+")},h.parse=function(n){function t(n){switch(n){case"http:":return 80;case"https:":return 443;default:return location.port}}var r=document.createElement("a");return r.href=n,{href:r.href,host:r.host||location.host,port:"0"===r.port||""===r.port?t(r.protocol):r.port,hash:r.hash,hostname:r.hostname||location.hostname,pathname:"/"!==r.pathname.charAt(0)?"/"+r.pathname:r.pathname,protocol:r.protocol&&":"!==r.protocol?r.protocol:location.protocol,search:r.search,query:h.qs(r.search.slice(1))}
},h.qs=function(n){if(!n)return{};var t=decodeURIComponent;return n.split("&").reduce(function(n,r){var e=r.indexOf("="),o=t(r.slice(0,e)),u=t(r.slice(e+1));if(!o)return n;var a=n[o];return i.isArray(a)?a.push(u):n[o]=a?[a,u]:u,n},{})},i(["width","height"]).forEach(function(n){o[n]=function(t){var r=t.getBoundingClientRect();return r[n]}}),o.position=function(n){var t=n.getBoundingClientRect(),r=document.documentElement,e=document.body,o=r.clientTop||e.clientTop||0,i=r.clientLeft||e.clientLeft||0,u=window.pageYOffset||r.scrollTop,a=window.pageXOffset||r.scrollLeft;
return{left:parseFloat(t.left)+a-i,top:parseFloat(t.top)+u-o}},o.loadJS=function(n){return new f(function(t,r){var e=document.getElementsByTagName("script")[0],o=document.createElement("script");o.src=n,o.async=!0,e.parentNode.insertBefore(o,e),o.onload=function(){o=null,t(o)},o.onerror=function(n){o=null,r(n)}})},o.ls=e("localStorage"),o.ss=e("sessionStorage");var d=o.eventHub=new c;return o.triggerTopNav=function(n,t,r,e){return"wise"===r.env?void d.$emit(n,t):void(e&&e.trigger(n,t))},o}),define("@baidu/ala-util/lodash",["require"],function(){function n(n,t){return n.push.apply(n,t),n
}function t(n,t,r,e){for(var o=n.length,i=r+(e?1:-1);e?i--:++i<o;)if(t(n[i],i,n))return i;return-1}function r(n){return function(t){return null==t?nr:t[n]}}function e(n){return function(t){return null==n?nr:n[t]}}function o(n,t,r,e,o){return o(n,function(n,o,i){r=e?(e=!1,n):t(r,n,o,i)}),r}function i(n,t){return x(t,function(t){return n[t]})}function u(n,t){return function(r){return n(t(r))}}function a(n){return n instanceof c?n:new c(n)}function c(n,t){this.__wrapped__=n,this.__actions__=[],this.__chain__=!!t
}function f(n,t,r){var e=n[t];Ir.call(n,t)&&jt(e,r)&&(r!==nr||t in n)||l(n,t,r)}function l(n,t,r){n[t]=r}function s(n,t,r){if("function"!=typeof n)throw new TypeError(rr);return setTimeout(function(){n.apply(nr,r)},t)}function p(n,t){var r=!0;return Ur(n,function(n,e,o){return r=!!t(n,e,o)}),r}function h(n,t,r){for(var e=-1,o=n.length;++e<o;){var i=n[e],u=t(i);if(null!=u&&(a===nr?u===u&&!0:r(u,a)))var a=u,c=i}return c}function d(n,t){var r=[];return Ur(n,function(n,e,o){t(n,e,o)&&r.push(n)}),r}function v(t,r,e,o,i){var u=-1,a=t.length;
for(e||(e=G),i||(i=[]);++u<a;){var c=t[u];r>0&&e(c)?r>1?v(c,r-1,e,o,i):n(i,c):o||(i[i.length]=c)}return i}function m(n,t){return n&&Jr(n,t,ue)}function g(n,t){return d(t,function(t){return kt(n[t])})}function b(n){return H(n)}function y(n,t){return n>t}function w(n){return It(n)&&b(n)==hr}function _(n,t,r,e,o){return n===t?!0:null==n||null==t||!It(n)&&!It(t)?n!==n&&t!==t:j(n,t,r,e,_,o)}function j(n,t,r,e,o,i){var u=Yr(n),a=Yr(t),c=u?lr:b(n),f=a?lr:b(t);c=c==fr?br:c,f=f==fr?br:f;var l=c==br,s=f==br,p=c==f;
i||(i=[]);var h=$r(i,function(t){return t[0]==n}),d=$r(i,function(n){return n[0]==t});if(h&&d)return h[1]==t;if(i.push([n,t]),i.push([t,n]),p&&!l){var v=u?J(n,t,r,e,o,i):K(n,t,c,r,e,o,i);return i.pop(),v}if(!(r&COMPARE_PARTIAL_FLfuncToStringAG)){var m=l&&Ir.call(n,"__wrapped__"),g=s&&Ir.call(t,"__wrapped__");if(m||g){var y=m?n.value():n,w=g?t.value():t,v=o(y,w,r,e,i);return i.pop(),v}}if(!p)return!1;var v=V(n,t,r,e,o,i);return i.pop(),v}function O(n){return It(n)&&b(n)==wr}function T(n){return"function"==typeof n?n:null==n?Vt:("object"==typeof n?E:r)(n)
}function A(n,t){return t>n}function x(n,t){var r=-1,e=Ot(n)?Array(n.length):[];return Ur(n,function(n,o,i){e[++r]=t(n,o,i)}),e}function E(n){var t=Dr(n);return function(r){var e=t.length;if(null==r)return!e;for(r=Object(r);e--;){var o=t[e];if(!(o in r&&_(n[o],r[o],er|or)))return!1}return!0}}function k(n,t){return n=Object(n),dt(t,function(t,r){return r in n&&(t[r]=n[r]),t},{})}function S(n,t){return Vr(X(n,t,Vt),n+"")}function P(n,t,r){var e=-1,o=n.length;0>t&&(t=-t>o?0:o+t),r=r>o?o:r,0>r&&(r+=o),o=t>r?0:r-t>>>0,t>>>=0;
for(var i=Array(o);++e<o;)i[e]=n[e+t];return i}function I(n){return P(n,0,n.length)}function F(n,t){var r;return Ur(n,function(n,e,o){return r=t(n,e,o),!r}),!!r}function C(t,r){var e=t;return dt(r,function(t,r){return r.func.apply(r.thisArg,n([t],r.args))},e)}function q(n,t){if(n!==t){var r=n!==nr,e=null===n,o=n===n,i=!1,u=t!==nr,a=null===t,c=t===t,f=!1;if(!a&&!f&&!i&&n>t||i&&u&&c&&!a&&!f||e&&u&&c||!r&&c||!o)return 1;if(!e&&!i&&!f&&t>n||f&&r&&o&&!e&&!i||a&&r&&o||!u&&o||!c)return-1}return 0}function B(n,t,r,e){var o=!r;
r||(r={});for(var i=-1,u=t.length;++i<u;){var a=t[i],c=e?e(r[a],n[a],a,r,n):nr;c===nr&&(c=n[a]),o?l(r,a,c):f(r,a,c)}return r}function N(n){return S(function(t,r){var e=-1,o=r.length,i=o>1?r[o-1]:nr;for(i=n.length>3&&"function"==typeof i?(o--,i):nr,t=Object(t);++e<o;){var u=r[e];u&&n(t,u,e,i)}return t})}function M(n,t){return function(r,e){if(null==r)return r;if(!Ot(r))return n(r,e);for(var o=r.length,i=t?o:-1,u=Object(r);(t?i--:++i<o)&&e(u[i],i,u)!==!1;);return r}}function R(n){return function(t,r,e){for(var o=-1,i=Object(t),u=e(t),a=u.length;a--;){var c=u[n?a:++o];
if(r(i[c],c,i)===!1)break}return t}}function D(n){return function(){var t=arguments,r=Lr(n.prototype),e=n.apply(r,t);return Pt(e)?e:r}}function W(n){return function(t,r,e){var o=Object(t);if(!Ot(t)){var i=T(r,3);t=ue(t),r=function(n){return i(o[n],n,o)}}var u=n(t,r,e);return u>-1?o[i?t[u]:u]:nr}}function L(n,t,r,e){function o(){for(var t=-1,a=arguments.length,c=-1,f=e.length,l=Array(f+a),s=this&&this!==Er&&this instanceof o?u:n;++c<f;)l[c]=e[c];for(;a--;)l[c++]=arguments[++t];return s.apply(i?r:this,l)
}if("function"!=typeof n)throw new TypeError(rr);var i=t&ir,u=D(n);return o}function U(n,t,r,e){return n===nr||jt(n,Pr[r])&&!Ir.call(e,r)?t:n}function J(n,t,r,e,o,i){var u=r&er,a=n.length,c=t.length;if(a!=c&&!(u&&c>a))return!1;for(var f=-1,l=!0,s=r&or?[]:nr;++f<a;){var p,h=n[f],d=t[f];if(p!==nr){if(p)continue;l=!1;break}if(s){if(!F(t,function(n,t){return et(s,t)||h!==n&&!o(h,n,r,e,i)?void 0:s.push(t)})){l=!1;break}}else if(h!==d&&!o(h,d,r,e,i)){l=!1;break}}return l}function K(n,t,r){switch(r){case pr:case hr:case gr:return jt(+n,+t);
case dr:return n.name==t.name&&n.message==t.message;case wr:case _r:return n==t+""}return!1}function V(n,t,r,e,o,i){var u=r&er,a=ue(n),c=a.length,f=ue(t),l=f.length;if(c!=l&&!u)return!1;for(var s=c;s--;){var p=a[s];if(!(u?p in t:Ir.call(t,p)))return!1}for(var h=!0,d=u;++s<c;){p=a[s];var v,m=n[p],g=t[p];if(!(v===nr?m===g||o(m,g,r,e,i):v)){h=!1;break}d||(d="constructor"==p)}if(h&&!d){var b=n.constructor,y=t.constructor;b!=y&&"constructor"in n&&"constructor"in t&&!("function"==typeof b&&b instanceof b&&"function"==typeof y&&y instanceof y)&&(h=!1)
}return h}function $(n){return Vr(X(n,nr,nt),n+"")}function G(n){return Yr(n)||Xr(n)}function z(n){var t=[];if(null!=n)for(var r in Object(n))t.push(r);return t}function H(n){return Br.call(n)}function X(n,t,r){return t=Wr(t===nr?n.length-1:t,0),function(){for(var e=arguments,o=-1,i=Wr(e.length-t,0),u=Array(i);++o<i;)u[o]=e[t+o];o=-1;for(var a=Array(t+1);++o<t;)a[o]=e[o];return a[t]=r(u),n.apply(this,a)}}function Y(n){return d(n,Boolean)}function Q(){var t=arguments.length;if(!t)return[];for(var r=Array(t-1),e=arguments[0],o=t;o--;)r[o-1]=arguments[o];
return n(Yr(e)?I(e):[e],v(r,1))}function Z(n,r,e){var o=null==n?0:n.length;if(!o)return-1;var i=null==e?0:ne(e);return 0>i&&(i=Wr(o+i,0)),t(n,T(r,3),i)}function nt(n){var t=null==n?0:n.length;return t?v(n,1):[]}function tt(n){var t=null==n?0:n.length;return t?v(n,ar):[]}function rt(n){return n&&n.length?n[0]:nr}function et(n,t,r){var e=null==n?0:n.length;r="number"==typeof r?0>r?Wr(e+r,0):r:0;for(var o=(r||0)-1,i=t===t;++o<e;){var u=n[o];if(i?u===t:u!==u)return o}return-1}function ot(n){var t=null==n?0:n.length;
return t?n[t-1]:nr}function it(n,t,r){var e=null==n?0:n.length;return t=null==t?0:+t,r=r===nr?e:+r,e?P(n,t,r):[]}function ut(n){var t=a(n);return t.__chain__=!0,t}function at(n,t){return t(n),n}function ct(n,t){return t(n)}function ft(){return C(this.__wrapped__,this.__actions__)}function lt(n,t,r){return t=r?nr:t,p(n,T(t))}function st(n,t){return d(n,T(t))}function pt(n,t){return Ur(n,T(t))}function ht(n,t){return x(n,T(t))}function dt(n,t,r){return o(n,T(t),r,arguments.length<3,Ur)}function vt(n){return null==n?0:(n=Ot(n)?n:Dr(n),n.length)
}function mt(n,t,r){return t=r?nr:t,F(n,T(t))}function gt(n,t){var e=0;return t=T(t),x(x(n,function(n,r,o){return{value:n,index:e++,criteria:t(n,r,o)}}).sort(function(n,t){return q(n.criteria,t.criteria)||n.index-t.index}),r("value"))}function bt(n,t){var r;if("function"!=typeof t)throw new TypeError(rr);return n=ne(n),function(){return--n>0&&(r=t.apply(this,arguments)),1>=n&&(t=nr),r}}function yt(n){if("function"!=typeof n)throw new TypeError(rr);return function(){var t=arguments;return!n.apply(this,t)
}}function wt(n){return bt(2,n)}function _t(n){return Pt(n)?Yr(n)?I(n):B(n,Dr(n)):n}function jt(n,t){return n===t||n!==n&&t!==t}function Ot(n){return null!=n&&St(n.length)&&!kt(n)}function Tt(n){return n===!0||n===!1||It(n)&&b(n)==pr}function At(n){return Ot(n)&&(Yr(n)||Nt(n)||kt(n.splice)||Xr(n))?!n.length:!Dr(n).length}function xt(n,t){return _(n,t)}function Et(n){return"number"==typeof n&&Rr(n)}function kt(n){if(!Pt(n))return!1;var t=b(n);return t==vr||t==mr||t==sr||t==yr}function St(n){return"number"==typeof n&&n>-1&&n%1==0&&cr>=n
}function Pt(n){var t=typeof n;return null!=n&&("object"==t||"function"==t)}function It(n){return null!=n&&"object"==typeof n}function Ft(n){if(!It(n)||"[object Object]"!=b(n))return!1;var t=Object.getPrototypeOf(n);if(null===t)return!0;var r=Ir.call(t,"constructor")&&t.constructor;return"function"==typeof r&&r instanceof r&&Cr.call(r)==qr}function Ct(n){return Bt(n)&&n!=+n}function qt(n){return null===n}function Bt(n){return"number"==typeof n||It(n)&&b(n)==gr}function Nt(n){return"string"==typeof n||!Yr(n)&&It(n)&&b(n)==_r
}function Mt(n){return n===nr}function Rt(n){return Ot(n)?n.length?I(n):[]:Jt(n)}function Dt(n){return"string"==typeof n?n:null==n?"":n+""}function Wt(n,t){var r=Lr(n);return null==t?r:re(r,t)}function Lt(n,t){return null!=n&&Ir.call(n,t)}function Ut(n,t,r){var e=null==n?nr:n[t];return e===nr&&(e=r),kt(e)?e.call(n):e}function Jt(n){return null==n?[]:i(n,ue(n))}function Kt(n){return n=Dt(n),n&&Or.test(n)?n.replace(jr,kr):n}function Vt(n){return n}function $t(n){return E(re({},n))}function Gt(t,r,e){var o=ue(r),i=g(r,o);
null!=e||Pt(r)&&(i.length||!o.length)||(e=r,r=t,t=this,i=g(r,ue(r)));var u=!(Pt(e)&&"chain"in e&&!e.chain),a=kt(t);return Ur(i,function(e){var o=r[e];t[e]=o,a&&(t.prototype[e]=function(){var r=this.__chain__;if(u||r){var e=t(this.__wrapped__),i=e.__actions__=I(this.__actions__);return i.push({func:o,args:arguments,thisArg:t}),e.__chain__=r,e}return o.apply(t,n([this.value()],arguments))})}),t}function zt(){}function Ht(n){var t=++Fr;return Dt(n)+t}function Xt(n){return n&&n.length?h(n,Vt,y):nr}function Yt(n){return n&&n.length?h(n,Vt,A):nr
}function Qt(n,t,r){function e(t){var r=p,e=h;return p=h=nr,b=t,v=n.apply(e,r)}function o(n){return b=n,m=setTimeout(a,t),y?e(n):v}function i(n){var r=n-g,e=n-b,o=t-r;return w?Math.min(o,d-e):o}function u(n){var r=n-g,e=n-b;return g===nr||r>=t||0>r||w&&e>=d}function a(){var n=Date.now();return u(n)?c(n):void(m=setTimeout(a,i(n)))}function c(n){return m=nr,_&&p?e(n):(p=h=nr,v)}function f(){m!==nr&&clearTimeout(m),b=0,p=g=h=m=nr}function l(){return m===nr?v:c(Date.now())}function s(){var n=Date.now(),r=u(n);
if(p=Sr.slice.call(arguments),h=this,g=n,r){if(m===nr)return o(g);if(w)return m=setTimeout(a,t),e(g)}return m===nr&&(m=setTimeout(a,t)),v}var p,h,d,v,m,g,b=0,y=!1,w=!1,_=!0;if("function"!=typeof n)throw new TypeError("Expected a function");return t=+t||0,Pt(r)&&(y=!!r.leading,w="maxWait"in r,d=w?Math.max(+r.maxWait||0,t):d,_="trailing"in r?!!r.trailing:_),s.cancel=f,s.flush=l,s}function Zt(n,t,r){var e=!0,o=!0;if("function"!=typeof n)throw new TypeError("Expected a function");return Pt(r)&&(e="leading"in r?!!r.leading:e,o="trailing"in r?!!r.trailing:o),Qt(n,t,{leading:e,maxWait:t,trailing:o})
}var nr,tr="4.17.4",rr="Expected a function",er=1,or=2,ir=1,ur=32,ar=1/0,cr=9007199254740991,fr="[object Arguments]",lr="[object Array]",sr="[object AsyncFunction]",pr="[object Boolean]",hr="[object Date]",dr="[object Error]",vr="[object Function]",mr="[object GeneratorFunction]",gr="[object Number]",br="[object Object]",yr="[object Proxy]",wr="[object RegExp]",_r="[object String]",jr=/[&<>"']/g,Or=RegExp(jr.source),Tr={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},Ar="object"==typeof global&&global&&global.Object===Object&&global,xr="object"==typeof self&&self&&self.Object===Object&&self,Er=Ar||xr||Function("return this")(),kr=e(Tr),Sr=Array.prototype,Pr=Object.prototype,Ir=Pr.hasOwnProperty,Fr=0,Cr=Function.prototype.toString,qr=Cr.call(Object),Br=Pr.toString,Nr=Object.create,Mr=Pr.propertyIsEnumerable,Rr=Er.isFinite,Dr=u(Object.keys,Object),Wr=Math.max,Lr=function(){function n(){}return function(t){if(!Pt(t))return{};
if(Nr)return Nr(t);n.prototype=t;var r=new n;return n.prototype=nr,r}}();c.prototype=Lr(a.prototype),c.prototype.constructor=c;var Ur=M(m),Jr=R(),Kr=zt,Vr=Vt,$r=W(Z),Gr=S(function(n,t,r){return L(n,ir|ur,t,r)}),zr=S(function(n,t){return s(n,1,t)}),Hr=S(function(n,t,r){return s(n,te(t)||0,r)}),Xr=Kr(function(){return arguments}())?Kr:function(n){return It(n)&&Ir.call(n,"callee")&&!Mr.call(n,"callee")},Yr=Array.isArray,Qr=w,Zr=O,ne=Number,te=Number,re=N(function(n,t){B(t,Dr(t),n)}),ee=N(function(n,t){B(t,z(t),n)
}),oe=N(function(n,t,r,e){B(t,ae(t),n,e)}),ie=S(function(n){return n.push(nr,U),oe.apply(nr,n)}),ue=Dr,ae=z,ce=$(function(n,t){return null==n?{}:k(n,t)}),fe=T;return a.assignIn=ee,a.before=bt,a.bind=Gr,a.chain=ut,a.compact=Y,a.concat=Q,a.create=Wt,a.defaults=ie,a.defer=zr,a.delay=Hr,a.filter=st,a.flatten=nt,a.flattenDeep=tt,a.iteratee=fe,a.keys=ue,a.map=ht,a.matches=$t,a.mixin=Gt,a.negate=yt,a.once=wt,a.pick=ce,a.slice=it,a.sortBy=gt,a.tap=at,a.thru=ct,a.toArray=Rt,a.values=Jt,a.debounce=Qt,a.throttle=Zt,a.extend=ee,a.assign=ee,Gt(a,a),a.clone=_t,a.escape=Kt,a.every=lt,a.find=$r,a.forEach=pt,a.has=Lt,a.head=rt,a.identity=Vt,a.indexOf=et,a.isArguments=Xr,a.isArray=Yr,a.isBoolean=Tt,a.isDate=Qr,a.isEmpty=At,a.isEqual=xt,a.isFinite=Et,a.isFunction=kt,a.isNaN=Ct,a.isNull=qt,a.isNumber=Bt,a.isObject=Pt,a.isPlainObject=Ft,a.isRegExp=Zr,a.isString=Nt,a.isUndefined=Mt,a.last=ot,a.max=Xt,a.min=Yt,a.noop=zt,a.reduce=dt,a.result=Ut,a.size=vt,a.some=mt,a.uniqueId=Ht,a.each=pt,a.first=rt,Gt(a,function(){var n={};
return m(a,function(t,r){Ir.call(a.prototype,r)||(n[r]=t)}),n}(),{chain:!1}),a.VERSION=tr,Ur(["pop","join","replace","reverse","split","push","shift","sort","splice","unshift"],function(n){var t=(/^(?:replace|split)$/.test(n)?String.prototype:Sr)[n],r=/^(?:push|sort|unshift)$/.test(n)?"tap":"thru",e=/^(?:pop|join|replace|shift)$/.test(n);a.prototype[n]=function(){var n=arguments;if(e&&!this.__chain__){var o=this.value();return t.apply(Yr(o)?o:[],n)}return this[r](function(r){return t.apply(Yr(r)?r:[],n)
})}}),a.prototype.toJSON=a.prototype.valueOf=a.prototype.value=ft,a}),define("@baidu/ala-util",["@baidu/ala-util/index"],function(n){return n});;;
